treasure-data/td

spec/file_reader/line_reader_spec.rb

Ensuring that external_encoding is differ from the original external_encoding,
the spec can check whether specified encoding will be applied to target io.
Before fixing, this spec failed only ruby ver. is 2.0+ (because default encoding became utf-8)
```
toriis-MacBook-Air:td toriiyuki$ rbenv local 2.2.0
toriis-MacBook-Air:td toriiyuki$ be rspec spec/file_reader/line_reader_spec.rb
.F....................
Failures:
1) TreasureData::FileReader::LineReader initialize with specifid encoding
Failure/Error: io.external_encoding.should_not == ee
expected not: == #<Encoding:UTF-8>
got:    #<Encoding:UTF-8>
Diff:UTF-8.==(UTF-8) returned false even though the diff between UTF-8 and UTF-8 is empty. Check the implementation of UTF-8.==.
Finished in 0.00845 seconds
22 examples, 1 failure
```

Fix FileReader::LineReader encoding spec.

---

lib/td/file_reader.rb

to raise it when MessagePackParsingReader forwards to end of io
and cannot read more, and rescue the exception in parsing.
Without this, in file_reader_spec.rb context 'msgpack' fails.
But I'm not sure that this PR satisfies td specification. Please give me your comments @frsyuki , @nahi .
fixed failures.
```
1) TreasureData::FileReader parse msgpack it should behave like parse --time-value / --time-column cases parse msgpack with --time-value
Failure/Error: reader.parse(io, error) { |record|
NoMethodError:
undefined method `[]=' for nil:NilClass
Shared Example Group: "parse --time-value / --time-column cases" called from ./spec/file_reader_spec.rb:324
2) TreasureData::FileReader parse msgpack it should behave like parse --time-value / --time-column cases parse msgpack with --time-column …
```

Add MessagePackEOFError

---

lib/td/command/job.rb
spec/td/command/job_spec.rb

The fix in 9d74b44b533878ee5f2a84db3506279f87f85bef at 0.11.7 broke the
job:show command when the download format is CSV or TSV and the target
query result contains non UTF-8 encoded byte sequence.
0.11.6 and before does transcoding and *sanitizes* non UTF-8 byte
sequence before saving to file. So the generated file is always in
UTF-8, but could be broken when query result is not in UTF-8.
0.11.7 simply removes that transcoding logic by
9d74b44b533878ee5f2a84db3506279f87f85bef for performance and crashes for
non UTF-8 encoded byte sequence.
This commit fixes 0.11.7 and saves non UTF-8 encoded byte sequence as-is
(through 'BINARY' encoding) so that the generated file should be
properly encoded in UTF-8, Shift_JIS, or whatever.

fix: save CSV/TSV file without transcoding

---

lib/td/updater.rb

jar_update changes current directory to ~/.td/java. But it doesn't changed back to original current directory.
https://github.com/treasure-data/td/blob/master/lib/td/updater.rb#L333

fix: changed back to original current directory when jar_update finished

---

td.gemspec

This reduces package size dramatically because `dist` directly has 13MB ruby pkg.

Remove dist dir from gem content

---

lib/td/command/job.rb
spec/td/command/job_spec.rb

this option enables to show null value as specified string in csv and tsv format.
ex.
```
td job:show 12345 --null  STRING
```
Please check it @nahi san.

Add --null option to job:show command.

---

lib/td/command/job.rb
spec/td/command/job_spec.rb

in csv and tsv.
When value of jobs result includes not finite float value,  Yajl will raise Yajl::EncodeError in `#dump`.
So check the value and convert infinite one to string before passing it to Yajl.dump in csv/tsv.

Sanitize NaN value of column for Yajl

---

lib/td/command/job.rb

I found a problem on exporting result as tsv format with column-header.
```
$ td job:show <jobid> -f tsv -o ./result.tsv --column-header
```
tab is unnecessary at the end of line.
```
name<tab>count<tab>
abc<tab>123
def<tab>456
```
I have fixed the behavior.
```
name<tab>count
abc<tab>123
def<tab>456
```

removing useless tab for tsv at the end of line of header

---

lib/td/command/common.rb
lib/td/command/job.rb
spec/td/command/job_spec.rb

This PR supports to show `job#duration` by `td job:list` command. This PR needs https://github.com/treasure-data/td-client-ruby/pull/43, so before this PR is merged, `td-client-ruby#43` should be merged and released.

Show job duration by job list

---

lib/td/command/job.rb
spec/td/command/job_spec.rb

Fix #47 
`write_result` method will be called by `job:show` and `query` sub command.

Fix #47 save as temporary file in downloading progress

---

lib/td/command/job.rb
lib/td/command/list.rb
lib/td/command/options.rb
lib/td/command/sched.rb
spec/td/command/sched_spec.rb

usage
```
% td sched:result <name> --last 1 -o output_file.csv -f csv
```
It shows `job:show` result without job_id, only by the num from the latest job.
`--last N` enables to specify  the num.
- --last => show the latest job result
- --last 2 => 2nd latest
- --last 3 => 3rd...

Add sched:result command

---

lib/td/command/account.rb
lib/td/command/acl.rb
lib/td/command/apikey.rb
lib/td/command/bulk_import.rb
lib/td/command/common.rb
lib/td/command/connector.rb
lib/td/command/db.rb
lib/td/command/export.rb
lib/td/command/help.rb
lib/td/command/import.rb
lib/td/command/job.rb
lib/td/command/list.rb
lib/td/command/password.rb
lib/td/command/query.rb
lib/td/command/result.rb
lib/td/command/runner.rb
lib/td/command/sched.rb
lib/td/command/schema.rb
lib/td/command/server.rb
lib/td/command/status.rb
lib/td/command/table.rb
lib/td/command/update.rb
lib/td/command/user.rb
lib/td/updater.rb

Prepare for next job, e.g. adding silence option, output refactoring, etc.
Always use `$stdout.puts` is grep/sed friendly.

Use fully quallified output methods such as $stdout.puts instead puts

---

lib/td/helpers.rb
spec/td/command/table_spec.rb

Fix #54 
`format_with_delimiter` method is already covered by this spec.
https://github.com/treasure-data/td/blob/master/spec/td/helpers_spec.rb

gsub without bang

---

lib/td/command/connector.rb
spec/td/command/connector_spec.rb

This commit needs https://github.com/treasure-data/td-client-ruby/pull/47 to be merged.
And since we no longer validates configuration for connector input configuration at client side, this PR includes emitting guessed config to stdout in config:guess to allow users check configuration by themselves. It closes #71.

Topic bulkload config validation free

---

lib/td/command/connector.rb

I've grepped then found that `client.bulk_load_*` API changes effect `td connector:*` commands only.
```console
$ git grep -n bulk_load_
lib/td/command/connector.rb:56:    job = client.bulk_load_guess(job)
lib/td/command/connector.rb:81:    preview = client.bulk_load_preview(job)
lib/td/command/connector.rb:121:    job_id = client.bulk_load_issue(database, table, job)
lib/td/command/connector.rb:139:    rows = client.bulk_load_list().sort_by { |e|
lib/td/command/connector.rb:175:    session = client.bulk_load_create(name, database, table, job, opts)
lib/td/command/connector.rb:183:    session = client.bulk_load_show(name)
lib/td/command/connector.rb:193:    session = client.bulk_load_update(name, job)
lib/td/command/connector.rb:201:    session = client.bulk_load_delete(name) …
```

Fix connector:show, update, delete, etc. fix #75

---

spec/td/command/connector_spec.rb

Connector spec will fail when the account has not been set.
I was corrected by imitating the other test.
@nahi , @yoshihara  Could you review this?

Fix connector spec when has no account

---

lib/td/command/connector.rb
lib/td/command/list.rb

Setting --access-id, --access-secret, and --source doesn't make sense
because now connector supports other data sources such as mysql.
This pull-request changes help message of connector:guess shown when
executed with no arguments to suggest users to use configuration file
rather showing "Error: --access-id option required".

connector:guess shows help message if no arguments are set

---

dist/pkg.rake

This reverts commit 39b182f55d7647109666f87d372134fdb2a23aba, reversing
changes made to b5e80ee24547ac4c5d7c586bd1c36fe444e97544.
because, fail SSL connection.

Revert "Merge pull request #96 from treasure-data/version_up_to_2.2.2_for_mac

---

dist/exe.rake
td.gemspec

because, `td upgrade` can't upgrade bundled ruby version.

Downgrade windows ruby version and td client

---

lib/td/command/job.rb
lib/td/command/options.rb
lib/td/command/query.rb
spec/td/command/job_spec.rb

support `msgpack.gz` format in query command.
And, I found `td job:show -f msgpack.gz` is saved decompressed file.
So, I fix that save gz fromated file.
This need https://github.com/treasure-data/td-client-ruby/pull/58.

support `msgpack.gz` format in query command, and fix save gz format

---

lib/td/command/query.rb

`job:show` is retry when show result. But, `query -w` dosen't retry.
This pull request allow retry when `query -w`.

show query command result with retry

---

lib/td/command/connector.rb

`connector:history` was broken from 0.11.10.
It's support following commit.
https://github.com/treasure-data/td-client-ruby/commit/e5226f383c4ccffcb8b77b88989c33d3268d9af4

fix data format that return from td-client#bulk_load-history

---

lib/td/command/common.rb
spec/td/common_spec.rb
td.gemspec

ref #45
So, Now it has become to look like the following.
| indicator | status | image |
|------------|-----------|-----------|
| TimeBasedDownloadProgressIndicator | progress | ![](https://cloud.githubusercontent.com/assets/43500/8471585/cb0965e4-20d4-11e5-8efa-532367eb3368.png) |
| TimeBasedDownloadProgressIndicator | finished | ![](https://cloud.githubusercontent.com/assets/43500/8471589/e5561776-20d4-11e5-8ac6-64380486859d.png) |
| SizeBasedDownloadProgressIndicator with total_size | progress |![](https://cloud.githubusercontent.com/assets/43500/8471621/2f4e8e62-20d5-11e5-8930-182c7971f180.png)
| SizeBasedDownloadProgressIndicator with total_size | finished |  ![](https://cloud.githubusercontent.com/assets/43500/8471597/0384ce22-20d5-11e5-9401-0186076f0225.png) |
| …

DownloadProgressIndicator with 'ruby-progressbar'

---

lib/td/command/connector.rb
lib/td/compact_format_yamler.rb
spec/td/command/connector_spec.rb
spec/td/compact_format_yamler_spec.rb

ref #74 
I could not find the YAML library that can be used is compact format.
So, I implemented inheriting the psych.
---
```
---
in:
type: s3
access_key_id:
secret_access_key:
bucket: 
path_prefix: connector_issue_test
decoders:
- type: gzip
parser:
charset: UTF-8
newline: CRLF
type: csv
delimiter: ","
quote: "\""
escape: "\""
trim_if_not_quoted: false
skip_header_lines: 1
allow_extra_columns: false
allow_optional_columns: false
columns:
- name: id
type: long
- name: " company"
type: string
- name: " customer"
type: string
- name: " created_at"
type: timestamp
format: "%Y-%m-%d %H:%M:%S"
filters: []
out:
mode: append
```
```
---
in:
type: s3
access_key_id: 
secret_access_key: 
bucket: 
path_prefix: connector_issue_test
decoders:
- {type: gzip}
parser:
charset: UTF-8
newline: CRLF
type: …
```

connector::guess use flow format hash

---

lib/td/command/runner.rb

fix `ib/td/command/runner.rb:194:in `rescue in run': undefined method `split' for nil:NilClass (NoMethodError)`

fix api_backtrace nil case

---

lib/td/command/job.rb
lib/td/command/query.rb
spec/td/command/job_spec.rb

ref #118 
`td query` and `td job:show` render json with header name key . 
```
[{"code":200,"cnt":4981},
{"code":404,"cnt":17},
{"code":500,"cnt":2}]
```

job:show and query support `--column-header` option with json format

---

lib/td/command/connector.rb

show obsolute message, if use command line option.
```
Command line option is obsoleted. You should use configuration file.
```

more informative obsolute message for connector:guess

---

lib/td/command/connector.rb

* Drop config and config_diff column because those information in this
table is meaning less fragment of the whole data. You can see full
information by connector:show <name>
* Don't resize to show the full of the name column. (specify minimum
width of column is the best way, but hirb doesn't have such feature)
If someone uses config/config_diff column, please give me a feedback.

Don't resize resulted table of connector:list

---

dist/resources/pkg/postinstall

At least on OS X El Capitan it is hard to install something in /usr/bin.
And on other OSes, it is bad behavior to touch /usr/bin because it is
manged by OS distributor (OS itself and official package manager).
We, treasure data, should touch /usr/local.

Install symlink in /usr/local/bin

---

lib/td/updater.rb

* Since the regexp checks the return value of Dir.glob, it doesn't need
to check entries other than the last one.
* On windows path may be 8.3 short path name for example username,
previous check may fail by it.

path check regexp should check only the last entry

---

dist/resources/exe/td.bat

On Windows ARGV converts the result of GetCommandLineW() into the
locale encoding (through default external encoding ruby_set_argv),
even if lib/td/command/runner.rb has `Encoding.default_external = 'UTF-8'`,
because ARGV is set in the bootstrap phase.
-Eutf-8 resolves this.

Use -Eutf-8 to specify ARGV as UTF-8

---

lib/td/updater.rb

Write VERSION and td-import-java.version after download td-import.jar to avoid download failure breaks consistency.
Before c02476b1 (above fix) it may breaks consistency of jarfile status. This resets such situation.

Solid jar update

---

lib/td/command/sched.rb

td-client-ruby 0.8.79's create_schedule may return nil
https://github.com/treasure-data/td-client-ruby/pull/78

Support dummy schedule

---

.travis.yml
lib/td/command/query.rb
lib/td/command/runner.rb
spec/td/command/query_spec.rb

"Domain key" is an optional user-provided unique ID.
Users can include this ID with your `create` request to ensure idempotence.

Support `td query --domain-key=KEY`

---

lib/td/command/export.rb

We highly recommend to use line-json.gz or tsv.gz format.
https://docs.treasuredata.com/articles/bulk-export

Update help for tsv.gz

---

lib/td/command/connector.rb
lib/td/command/list.rb
spec/td/command/connector_spec.rb

The fields that can be updated are:
* renaming sessions
* change db
* change table
* change cron
* change timezone
* change delay
* change time column
* config
* this change is **backwards incompatible** since the 'config' is now an optional parameter as opposed to a mandatory one
* cron schedule update also support deletion of the cron to unschedule the session. To fully support this option changes in the APIs are necessary (refer to the [bulk_loads sessions controller](https://github.com/treasure-data/td-api/blob/master/app/controllers/api_v3/api_bulk_load_sessions_controller.rb#L98) ==> `params[:cron].present?` makes the empty cron parameter ignored, thus not allowing to _unset_ the cron specification)
CLT-827

Support rich update of Data Connector Session

---

lib/td/command/account.rb

This commit is for Google SSO user to know how to authorize td command. 
Google SSO users is not able to login via `td account`.
So, I would like to link the help.
https://docs.treasuredata.com/articles/command-line#google-sso-users

CLT-1096: Add an explanation for Google SSO users

---

td.gemspec

td-client-ruby already drops 1.9 support.
td CLI should drop 1.9.

Drop Ruby 1.9 support

---

lib/td/command/query.rb
lib/td/command/sched.rb

Remove mentions of "pig" as a valid type for these commands:
* `td query`
* `td sched:create`
* `td sched:update`

Deprecate Pig query engine

---

lib/td/command/workflow.rb

and workflow:version --help.
Without this `td workflow:reset --help` will just remove work flow module.

Show help for workflow:reset --help

---

lib/td/command/workflow.rb

Don't raise exception even if td.conf doesn't exist.

Avoid exception on downloading digdag

---

lib/td/command/workflow.rb
lib/td/config.rb
spec/spec_helper.rb
spec/td/command/workflow_spec.rb
spec/td/config_spec.rb

Where you should review:
* TREASURE_DATA_WORKFLOW_ENDPOINT: naming
* TD_API_KEY: maybe this should be TREASURE_DATA_API_KEY but digdag doesn't support it

Support workflow on aws tokyo

---

lib/td/command/workflow.rb
lib/td/config.rb

For `td workflow run foo.dig` whose dig file includes td operator,
digdag needs to call correct td-api endpoint which relates apikey,
but td command didn't pass it.

Pass td-api endpoint to digdag

---

lib/td/updater.rb

Automatic td update may spread issues when td-toolbelt has some bug.
Updating should be under controll for users who uses td-toolbelt on
Windows.

Remove auto td update

---

ChangeLog
dist/exe.rake
spec/td/updater_spec.rb

MSYS2's mingw32 environment doesn't work well; it show following error:
180 [main] ruby 3156 child_info_fork::abort: address space needed by 'console.so' (0x3F0000) is already occupied
I decide to use mingw64 from v0.16.

Use x64 binary

---

Rakefile

`build/update-td-import-java.sh` was removed by 76224634b0f00ea4ad635cc0ee4f678a942c7aa3.

Remove "jar" task

---

td.gemspec

This commit will suppress such warnings:
```
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.
Gem::Specification#has_rdoc= called from td/td.gemspec:13.
```
Ref: https://github.com/rubygems/rubygems/pull/2214/files#diff-05477d38d75c98664b0e7dec6eb73b45R2035

Remove deprecated gem specification

---

td.gemspec

Rubyzip < 1.3.0 is affected by CVE-2019-16892.
Even when this gem isn't directly affected by the CVE some automatic
vulnerability scanners can mark the gem as unsafe because of the
dependency version.
Related: https://github.com/rubyzip/rubyzip/pull/403
This closes https://github.com/treasure-data/td/issues/221

Bump minimum rubyzip version to 1.3.0

---

lib/td/command/workflow.rb
spec/td/command/workflow_spec.rb

This change use HTTPS as default for downloading digdag module
```
$ TD_TOOLBELT_DEBUG=1 td wf
Workflow module not yet installed, download now? [Y/n]
y
redirect 'https://toolbelt.treasuredata.com/digdag/jdk/mac_x64' to 'https://d3hq3slxjftf62.cloudfront.net/java/zulu8.17.0.3-jdk8.0.102-macosx_x64.zip'...                                                   
redirect 'https://toolbelt.treasuredata.com/digdag/jdk/mac_x64' to 'https://d3hq3slxjftf62.cloudfront.net/java/zulu8.17.0.3-jdk8.0.102-macosx_x64.zip'... 
Downloading Java...: done                                                                                                                                                                                   
Installing Java... done
redirect …
```

CLT-1474: Use HTTPS as default for downloading digdag module

---

lib/td/command/workflow.rb
spec/td/command/workflow_spec.rb
td.gemspec

add -Dclient.http.disable_direct_download=true command line argument if workflow server endpoint matches with /\.connect\./.

add -Dclient.http.disable_direct_download=true for private connection

---

.travis.yml
lib/td/command/workflow.rb

The existing code for Java versions supposes `1.8.0_56` style format.
But currently, latest LTS Java version format is `11.0.2`, so it doesn't work correctly.
This change is to fix that problem.

Support recent java versions

---

lib/td/command/common.rb
lib/td/command/runner.rb
lib/td/command/table.rb
lib/td/config.rb
spec/td/command/table_spec.rb

Now Treasure Data is providing `api-import.*` endpoints only for streaming import requests.
`api.*` endpoints can route/process those requests now and in future, but it's better to send those requests to `api-import` endpoints.

Send table:import requests to api-import endpoints directly

---

lib/td/command/runner.rb

The previous change #226 had a critical bug for `--import-endpoint` option to assign wrong value.
This change is to fix that.
The version with this change is actually working correctly on my laptop...

Fix bug of the value to assign

---

README.rdoc
lib/td/updater.rb

The current default no longer works.  See https://blog.sonatype.com/central-repository-moving-to-https

Use recommended Maven Central URL

---

lib/td/config.rb
spec/td/config_spec.rb

Update Workflow endpoint pattern to support ap02

---

td.gemspec

Updates the minimum version of the [yajl-ruby](https://github.com/brianmario/yajl-ruby) gem dependency to at least 1.3.1.  This is the minimum version necessary in order to mitigate [CVE-2017-16516](https://nvd.nist.gov/vuln/detail/CVE-2017-16516), which is present in yajl-ruby gem versions 1.3.0 and earlier.
`rake spec` tests passed successfully.
Environment:
* ruby 2.7.1

Force upgrade of yajl-ruby to at least 1.3.1, fixing CVE-2017-16516

---

td.gemspec

It is better to add licenses explicitly in gemspec.
% gem specification td | \grep licenses
licenses: []
ref. https://guides.rubygems.org/specification-reference/

Add missing licenses - Apache-2.0

---

lib/td/config.rb
spec/td/config_spec.rb

Currently, TD Toolbelt allows endpoints as follows:
- schema + host
- host
As we set endpoint with trailing slash in td.conf and/or environment variables such as `https://example.com/`, TD returns like:
```
$ td wf
TreasureData account is not configured yet.
Run 'td account' first.
```
It confuses users because the message doesn't tell us that
`account.endpoint` or environment vairables of endpoint is invalid.
Thus, I propose that the tool allows users to tailing slash as the endpoint
URIs.
What do you think about it?

Allow trailing slash for endpoints

---

lib/td/command/table.rb

I updated an error message which is ouput as running `td table:list` to an import-only database.
As executing `table:list` command, `td` outputs `cannot list or create tables`:
```
% td table:list akito_import_only
0 rows in set
Database 'akito_import_only' is import only, cannot list or create tables.
```
However, creating a new table was succeeded though the database is import-only like below:
```
% td table:create akito_import_only samples
Table 'akito_import_only.samples' is created.
```
Therefore, I cut "or create tables" from the former error message since it would be misleading and the command was `td table:list` but not `td table:create`.
If we output `cannot list or create tables` as before, we might need to restrict users from creating new tables to import-only tables because we …

Update error message when running `table:list` to import only DB

---

.circleci/config.yml
lib/td/command/common.rb
lib/td/config.rb
spec/td/config_spec.rb

There are two changes needed to support AP03:
- Update workflow regex pattern to support AP03 (in config.rb)
- Fix bug when no import_endpoint setting a met. If so, import endpoint should default to nil and get handled by td-client-ruby instead of defaulting to DEFAULT_IMPORT_ENDPOINT. (in common.rb)

Support AP03 Region

---

lib/td/command/export.rb
lib/td/command/runner.rb

The summary width of `--assume-role` option in `table:export` help message is exceeding the current default value (32), so the help message for `--assume-role` option is broken.
```
usage:
$ td table:export <db> <table>
......
-e, --encryption ENCRYPT_METHOD  export with server side encryption with the ENCRYPT_METHOD
-a ASSUME_ROLE_ARN,              export with assume role with ASSUME_ROLE_ARN as role arn
--assume-role
```
To fix the broken help message for `--assume-role` option, we need to increase the summary width. From here, we increase the value to 36. After increasing the summary width, we can see the proper help message for `--assume-role` option as the following:
```
usage:
$ td table:export <db> <table>
......
-e, --encryption ENCRYPT_METHOD      export with server side …
```

Increase the summary_width value to fix the broken options help message format

---

td.gemspec

Parallel version latter than 1.20 only support Ruby 2.5 and up. We need to pin parallel to version 1.20.x to support ruby 2.4.5.

Pin parallel version to support ruby 2.4.5

---

dist/resources/exe/td.iss
lib/td/updater.rb

This PR includes fixes for:
1. td gem version does not load correctly because previous versions also exists. Solution is to remove vendor/ folder first in the installing process.
2. `td update` throws exception if folder `.td` does not exist in HOME directory.

Bug fixes for installing and updating in Windows

---

td.gemspec

td-0.16.10 doesn't accept latest yajl-ruby (1.4.1) although td-0.16.9
accepts it (`>~ 1.3.1` means `>= 1.3.1, < 1.4`).
Probably fc71ccdb2c9a88cd72ba4262f493c81291fb3ac6 doesn't intend to
reject it, it seems a mistake:
Force upgrade of yujl-ruby to at least 1.3.1, fixing CVE-2017-16516 (#235)
Signed-off-by: Takuro Ashie <ashie@clear-code.com>

Relax required version of yajl-ruby

---

lib/td/command/account.rb
spec/td/command/account_spec.rb
td.gemspec

Ruby 3 has dropped `Win32API` gem, causing `td account` command to fail. We need to replace ` Win32API` with `fiddle`.
- Use `fiddle` directly for getting password in Windows.
- Add tests for account command.
- Windows builds

Fix account command error on windows

---

lib/td/command/user.rb

When we run `td user:create name -e {email_address} -R`, the generated random password includes `_`, `@`, `-`, `+` or `;`.
However, our current password rule requires other symbols: ! # $ % - _ = + < >. It means the current random password option has the possibility to violate a user's password policy.
Thus, I propose updating the characters which are used in `--random-password` option.
Although I couldn't add a test case because the password validation depends on TD account's setting and our API doesn't return the password. However, it worked on our local machine.
```
% be td user:create dummy-name -e {my_email_address} -R 
Password: EZdBr<8e0
User 'dummy-name' is created.
Use 'td user:apikeys dummy-name' to show the API key.
```

Update password symbol for user creation

---

spec/td/command/workflow_spec.rb
td.gemspec

As td-client gem version 2.0.0 is now available https://github.com/treasure-data/td-client-ruby/releases/tag/v2.0.0, we need to support it in td cli

Support td-client 2.x.x

---

bin/td
lib/td/command/workflow.rb
spec/td/command/workflow_spec.rb

So far there are 2 URLs are used to reference TD Toolbelt's download URL.
* https://toolbelt.treasuredata.com/
* https://toolbelt.treasure-data.com/
Since there is no particular reason to use 2 distinct URLs for it, I'd like to make it consistent to use https://toolbelt.treasuredata.com/ as the download URL for TD Toolbelt.

Use https://toolbelt.treasuredata.com/ for TD Toolbelt's download URL consistently
