treasure-data/td

lib/td/updater.rb
spec/td/updater_spec.rb

refs #39
Add spec for cwd doesn't change after jar update.

Add test for jar update cwd

---

lib/td/command/list.rb

Deleted an unnecessary td of example.

Delete an unnecessary td

---

lib/td/command/table.rb
spec/td/command/table_spec.rb

"123456" is "123,456" table format only.

#26 Don't format numbers if format is not 'table'

---

lib/td/command/query.rb

Option message should not show 'impala'

Disable impala comment

---

lib/td/command/bulk_import.rb
lib/td/command/export.rb
lib/td/command/query.rb
lib/td/command/table.rb

At this moment you cannot specify scheduled job's pool name.

Add --pool-name option to job registrations

---

lib/td/command/connector.rb
spec/td/command/connector_spec.rb
spec/td/fixture/bulk_load.yml

fixes #63.
before:
```
+------------------------------------------------------------------------------------------------+----------+----------+
| foohogeeeeeeeeeeeeeeeeeeeefoohogeeeeeeeeeeeeeeeeeeeefoohogeeeeeeeeeeeeeeeeeeeefoohogeeeeeee... | bar:long | baz:long |
+------------------------------------------------------------------------------------------------+----------+----------+
| 1                                                                                              | 2        | 3        |
| 2                                                                                              | 2        | 3        |
| 3                                                                                              | 4        | 5        | …
```

Show full column name (not truncated) by `connector:preview` command

---

Rakefile

Support `rake spec` command.
@nahi  Could you review and merge this?

Rakefile: Support spec task

---

td.gemspec

@takkanm Could you review and merge?

Add coveralls

---

lib/td/command/list.rb
lib/td/command/table.rb

Remove -t (to) and -f (from) from table:tail command.
https://github.com/treasure-data/td-client-ruby/commit/33e23abb402f923c1bc304ea9c011dc3ca9a7781
@uu59 Could you review and merge this?

Follow-up for td-client-ruby change

---

lib/td/command/connector.rb

fix #64 
Rescue from config_file load error, and show error message.

rescue load config_file error

---

.coveralls.yml
.gitignore
spec/spec_helper.rb
td.gemspec

fix https://github.com/treasure-data/td/pull/87

Fix simplecov version and setup coveralls

---

spec/td/updater_spec.rb

travice is not darwin and mswin.

fix fail spec in travice

---

appveyor.yml
dist/build_win81.sh
dist/exe.rake
dist/resources/exe/td.bat
dist/resources/exe/td.iss
lib/td/command/import.rb
spec/spec_helper.rb
spec/td/command/job_spec.rb

I have confirmed that the installation is successful in Windows.

Use Ruby 2.2.2 for Windows

---

lib/td/command/connector.rb

connector:* don't use extra config: key

---

lib/td/command/table.rb

Delete comments about 'item' table.
Because, we don't support item table now.

Delete comments about 'item' table

---

dist/pkg.rake

version up bundled ruby for Mac.

version up bundled ruby for Mac

---

lib/td/command/connector.rb
spec/td/command/connector_spec.rb

fix use undefiened local valiable

---

ChangeLog

fix this comment. https://github.com/treasure-data/td/commit/67d2265da25bdef62f9b31f9047b264c6ebb1b20#commitcomment-12315623

fix released version and date in Changelog

---

lib/td/command/common.rb
lib/td/command/connector.rb
lib/td/command/table.rb
spec/td/command/connector_spec.rb
spec/td/command/table_spec.rb
spec/td/common_spec.rb

connector:issue always create database if table doesn't exist. #68 
I am worried about when the typo of the table name.
Shall i add option ? (ex. --create or -c

connector:issue created database if table doesn't exist

---

spec/td/command/table_spec.rb

It's change
https://github.com/treasure-data/td-client-ruby/commit/3e68eacdcfa19a409960a0414133934912d8dadc

fix TreasureData::Table constructor interface

---

spec/spec_helper.rb
spec/td/command/import_spec.rb

add import:list, import:show, import:create

Add spec for import command

---

lib/td/command/runner.rb

support https://github.com/treasure-data/td-client-ruby/pull/60

improve show bactrace from server

---

dist/exe.rake
dist/pkg.rake
dist/resources/pkg/Distribution.erb
lib/td/updater.rb

Update bundled ruby version

---

lib/td/command/connector.rb
lib/td/connector_config_normalizer.rb
spec/td/command/connector_spec.rb
spec/td/connector_config_normalizer_spec.rb

support guess plugins that users want to use

add -g, --guess option for connector:config

---

lib/td/connector_config_normalizer.rb
spec/td/command/connector_spec.rb
spec/td/connector_config_normalizer_spec.rb

support filters section in connector

---

lib/td/command/connector.rb

`bulk_load.yml` → `config.yml`

rename default file name for guess

---

lib/td/command/connector.rb

`exclude` option is unused in wait_connector_job.

remove unuse `exclude` option

---

lib/td/command/connector.rb
lib/td/command/list.rb
lib/td/command/runner.rb
spec/td/command/connector_spec.rb

ref #123
And,  scheduled_time is changed as optional argument. When it is omitted, use current time.

Pass schedule time to bulk_load_run

---

lib/td/command/common.rb
lib/td/command/list.rb
lib/td/command/table.rb
spec/td/command/table_spec.rb

add table:rename command

---

lib/td/command/connector.rb

ref #129
connector:[list,show,create,delete,update] support thah show `config_diff` value.
```
$ td connector:list
+------------------+----------+------------+-------+-----------+-------+---------------------+-------------------+
| Name                 | Cron      | Timezone  | Delay | Database | Table | Config                   | Config_diff         |
+------------------+----------+------------+-------+-----------+-------+---------------------+-------------------+
| connector_test  | 0 * * * *   | UTC          | 0        |                 |          | {"in"=>{"type"=>... | {"in"=>{}}           |
+------------------+----------+------------+-------+-----------+-------+---------------------+-------------------+
```
```
$ td connector:show connector_test
Name     : connector_test
<snip> …
```

support rendering config diff

---

lib/td/command/connector.rb
spec/td/command/connector_spec.rb

api return start_at is nil if job is queueing
ref https://github.com/treasure-data/td/issues/128

fix connector hitory if hitory has queueing item

---

lib/td/command/table.rb

delete unused option

---

spec/td/command/import_spec.rb

this test case don't cleanup unnecessary file.

fix create unnecessary file in spec

---

spec/td/command/connector_spec.rb

add spec for connector:guess, connector:list, connector:create

Add connector spec for guess, list, create

---

lib/td/updater.rb

* uri query handling
* missing openssl require

fix Updater.stream_fetch bugs

---

lib/td/command/connector.rb
spec/td/command/connector_spec.rb

Support new API to update connector's config_diff field.

connector:update supports config_diff #127

---

.travis.yml
appveyor.yml
contrib/completion/_td
lib/td/command/common.rb
lib/td/command/list.rb
lib/td/command/runner.rb
lib/td/command/workflow.rb
lib/td/helpers.rb
spec/td/command/workflow_spec.rb
spec/td/helpers_spec.rb

~~This requires https://github.com/treasure-data/digdag/pull/226~~
This is now good to go.

add workflow command

---

contrib/completion/_td
lib/td/command/list.rb
lib/td/command/workflow.rb

```
$ td workflow:update
Downloading workflow module (digdag-latest) ...                                                                                                                                                             Downloading workflow module...: done
Installing workflow module... done
Done.
```
```
$ td workflow:update 0.9.1
Downloading workflow module (digdag-0.9.1) ...                                                                                                                                                              Downloading workflow module...: done
Installing workflow module... done
Done.
```
```
$ td workflow:update 0.8.22
Downloading workflow module (digdag-0.8.22) ... …
```

add workflow:update command

---

td.gemspec

Upgrade rubyzip dependency to 1.2.1

---

td.gemspec

This change is needed for td-agent 3.

Relax td-client gem dependency

---

contrib/completion/_td
lib/td/command/list.rb

Remove duplicated 'the's

---

lib/td/command/workflow.rb
lib/td/updater.rb

The original code doesn't support HTTP status code 301.

Fix the wrong handling of HTTP redirection

---

lib/td/command/list.rb
lib/td/command/table.rb
spec/td/command/table_spec.rb

NOTE: this command depends td-client.gem v1.0.5

table:update to update table options

---

lib/td/updater.rb
lib/td/version.rb

This expects: https://github.com/treasure-data/td-toolbelt/pull/9

Bump toolbelt version

---

README.rdoc
lib/td/command/account.rb
lib/td/command/table.rb

README and message for td command uses old document's url.
Let's update it!

Update urls for documents

---

README.rdoc
dist/exe.rake
dist/pkg.rake

Instead of bundle RubyInstaller, just download before packaging

Use Ruby 2.4.5

---

lib/td/command/list.rb

It is hard to know usage for this command. so i propose to enrich cli document.

Enrich export:result document

---

lib/td/config.rb
spec/td/config_spec.rb

Also, domain names are case-insensitive.

workflow_endpoint regexp needs to expect digits

---

README.rdoc
lib/td/command/account.rb
lib/td/command/runner.rb
lib/td/command/table.rb

I have fixed some old URLs to avoid confusing users.

Change old document urls to new document urls

---

lib/td/command/runner.rb

Currently there is no explanation for `td user` command in Basic command.
So I added `td user` to basic command list

Adding users commnad help

---

lib/td/command/common.rb

Added support for URLs with user/password in the HTTP_PROXY environment variable.

Support proxy with a username and password

---

.gitignore
ChangeLog
Rakefile
dist/build_osx.sh
dist/exe.rake
dist/pkg.rake
lib/td/updater.rb
lib/td/version.rb

Candidate v0.17.0

---

ChangeLog
lib/td/version.rb

Release 0.17.1

---

ChangeLog
lib/td/version.rb

Changelog
* Update password symbol for user creation #262
* Add support for td-client-ruby 2.x.x #267

Release v0.18.0

---

ChangeLog
lib/td/version.rb

Changelog:
* Use https://toolbelt.treasuredata.com/ for TD Toolbelt's download URL #270

Release version 0.18.1

---

ChangeLog
lib/td/version.rb
td.gemspec

Release v0.19.0
